# Generated by Django 3.0.10 on 2020-10-16 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=35)),
                ('is_client', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_login', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('category_icon', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=40)),
                ('style_price', models.IntegerField()),
                ('style_icon', models.ImageField(upload_to='style')),
                ('style_head', models.ImageField(upload_to='head')),
                ('style_hnc', models.ImageField(upload_to='hnc')),
                ('style_hnb', models.ImageField(upload_to='hnb')),
                ('style_fbody', models.ImageField(upload_to='fbody')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(default='JzfIw70w2r', max_length=12, primary_key=True, serialize=False)),
                ('date_request', models.DateField(default=django.utils.timezone.now)),
                ('order_image', models.ImageField(upload_to='order')),
                ('order_result', models.ImageField(default='#', upload_to='result')),
                ('is_remove_acc', models.BooleanField(default=False)),
                ('is_include_file', models.BooleanField(default=False)),
                ('is_fast', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
