# Generated by Django 3.0.10 on 2020-10-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201016_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='K86fe6dc0MnDvkiR', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='58Kkck8BbH', max_length=12, primary_key=True, serialize=False),
        ),
    ]
