# Generated by Django 3.0.10 on 2020-10-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201016_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='SakUWdLXct', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='ecOa4Zujc9gmpoxO', max_length=20, unique=True),
        ),
    ]
