# Generated by Django 3.0.10 on 2020-10-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201017_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='t4VxOiQOUZ', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='GLjRU7u09vL2UUJq', max_length=20, unique=True),
        ),
    ]
