# Generated by Django 3.0.10 on 2020-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201018_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='LIcy0Q5wmJ', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_image',
            field=models.ImageField(blank=True, null=True, upload_to='order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='cb1mMlE47P6A7n7m', max_length=20, unique=True),
        ),
    ]
