# Generated by Django 3.0.10 on 2020-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201018_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='carousel')),
                ('carousel_text', models.CharField(blank=True, max_length=160, null=True)),
                ('carousel_link', models.CharField(blank=True, max_length=160, null=True)),
                ('carousel_position', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='tXok4diwQC', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='2BpEv9LchSpUN5lj', max_length=20, unique=True),
        ),
    ]
