# Generated by Django 3.0.10 on 2020-10-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201019_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_gallery', models.ImageField(upload_to='gallery')),
                ('type_gallery', models.CharField(max_length=130)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='hzsFkyOhMt', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='Rf1FKE386aJfs0GO', max_length=20, unique=True),
        ),
    ]
