# Generated by Django 3.0.10 on 2020-10-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201024_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='type_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='m9HvgtvCJX', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_user',
            field=models.CharField(default='UCgpZMLRQQwF8CQz', max_length=20, unique=True),
        ),
    ]
