# Generated by Django 3.0.10 on 2020-10-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201030_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_image',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='sjHTTyczqt', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='imageorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_image', models.ImageField(upload_to='order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.order')),
            ],
        ),
    ]
